# Remote control
allow_remote_control yes

# Theme
include current-theme.conf
background #000000

# Transparency
background_opacity 0.80
background_blur 20

# Font
font_family JetBrainsMono Nerd Font DemiBold
font_size 12.0
modify_font cell_height 130%

# Window
hide_window_decorations titlebar-only
window_padding_width 0 4

# Tab bar
tab_bar_min_tabs 2

# Cursor
cursor_shape beam
cursor_blink_interval 0.5

# Cursor trail
cursor_trail 1
cursor_trail_decay 0.05 0.2
cursor_trail_start_threshold 2

# macOS
macos_option_as_alt yes
macos_titlebar_color background
