# Remote control
allow_remote_control yes

# Theme
include current-theme.conf
background #000000

# Transparency
background_opacity 0.80
background_blur 20

# Font
font_family      JetBrainsMono Nerd Font Mono
bold_font        JetBrainsMono Nerd Font Mono Extra Bold
bold_italic_font JetBrainsMono Nerd Font Mono Extra Bold Italic
font_size 11.5
text_composition_strategy legacy
modify_font cell_height 12px

# Window
hide_window_decorations titlebar-only
window_padding_width 0 4

# Tab bar
tab_bar_min_tabs 2

# Cursor
cursor_shape beam
cursor_blink_interval 0.5

# Cursor trail
cursor_trail 2
cursor_trail_decay 0.05 0.2
cursor_trail_start_threshold 3

# Keymaps
map cmd+k send_text all \x1bK

# macOS
macos_option_as_alt yes
macos_titlebar_color background
